version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    ports:
      - "3002:3000"
      - "2223:22"
    volumes:
      - gitea_data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000


      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR=smtp.gmail.com
      - GITEA__mailer__SMTP_PORT=465
      - GITEA__mailer__USER=annrosethomson5@gmail.com
      - GITEA__mailer__PASSWD=yvqmuuelybhijmnj
      - GITEA__mailer__FROM=annrosethomson5@gmail.com

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  gitea_data:
